### ISSUE TITLE
Boss Sketch for Spider

### ISSUE THREAD

**Issue by Eszopa02** [ReviveZygarde/2D-PINBALL-Protoype#41]
Look at the Bosses category in the [Moodboard](https://miro.com/app/board/uXjVNQTFhzQ=/)

**Comment by PsychoInsanityX** [comment]
I'll do this sketch if no one took this assign

**Comment by PsychoInsanityX** [comment]
Color is coming soon!

**Comment by PsychoInsanityX** [comment]
![Spider](https://github.com/ReviveZygarde/2D-PINBALL-Protoype/assets/150479945/f4647d80-a68a-48d7-b086-82290fad1bd2)
