### ISSUE TITLE
Roulette Wheel 2D Asset

### ISSUE THREAD

**Issue by Eszopa02** [ReviveZygarde/2D-PINBALL-Protoype#43]
Create a 2D asset of a roulette wheel, reference the [Moodboard](https://miro.com/app/board/uXjVNQTFhzQ=/)

**Comment by PsychoInsanityX** [comment]
It's finished!
![Routelle Wheel](https://github.com/ReviveZygarde/2D-PINBALL-Protoype/assets/150479945/8bc40658-36cf-489f-9a56-dc1f0a2dba3f)
